# PIM447 is on the right hand side and must be connected to CENTRAL. So we make
# the right half CENTRAL.
CONFIG_ZMK_KEYBOARD_NAME="PIM-DS87"
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# Turn on logging, and set ZMK logging to debug output
# CONFIG_ZMK_USB_LOGGING=y
# CONFIG_SENSOR_LOG_LEVEL_DBG=y
# CONFIG_ZMK_LOG_LEVEL_DBG=y

CONFIG_INPUT=y
CONFIG_I2C=y
# CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

# Enables/disables all battery level detection/reporting
CONFIG_ZMK_BATTERY_REPORTING=y
# Battery level report interval in seconds
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60
# Enable central reporting of split battery levels to hosts
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
# Enable fetching split peripheral battery levels to the central side
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y