manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: m165437 #nice-gem
      url-base: https://github.com/M165437 #nice-gem
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      # revision: refs/pull/961/head
      import: app/west.yml
    - name: nice-view-gem #nice-gem
      remote: m165437 #nice-gem
      revision: main #nice-gem
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
  self:
    path: config
