manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/twinoner
  projects:
    - name: zmkfirmware
      remote: zmk
      # revision: try-pim447
      revision: main
      import: app/west.yml
  self:
    path: config
