manifest:
  remotes:
    # - name: zmkfirmware
    #   url-base: https://github.com/zmkfirmware
    - name: zmkfirmware
      url-base: https://github.com/t0bybr
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: m165437 #nice-gem
      url-base: https://github.com/M165437 #nice-gem
  projects:
    - name: zmk
      remote: zmkfirmware
      # revision: main
      revision: pr2477
      import: app/west.yml
    - name: nice-view-gem #nice-gem
      remote: m165437 #nice-gem
      revision: main #nice-gem
  self:
    path: config
