manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/twinoner
  projects:
    - name: zmk
      remote: zmk
      revision: tree/try-pim447
      # revision: main
      import: app/west.yml
  self:
    path: config
