manifest:
  remotes:
    # - name: zmk_ds87
    #   url-base: https://github.com/daniel2887
    - name: zmk
      url-base: https://github.com/cdc-mkb
    # - name: m165437 #nice-gem
    #   url-base: https://github.com/M165437 #nice-gem
  projects:
    - name: zmk
      remote: zmk
      revision: mouse-pim447
      import: app/west.yml
    # - name: nice-view-gem #nice-gem
    #   remote: m165437 #nice-gem
    #   revision: main #nice-gem
  self:
    path: config
