manifest:
  remotes:
    - name: zmk_trypim447
      url-base: https://github.com/twinoner
    # - name: zmk_ds87
    #   url-base: https://github.com/daniel2887
    # - name: m165437 #nice-gem
    #   url-base: https://github.com/M165437 #nice-gem
  projects:
    - name: zmk
      remote: zmk_trypim447
      revision: cdc-mkb-pim447
      import: app/west.yml
    # - name: zmk
    #   remote: zmk_ds87
    #   revision: ds87-mouse-pim447
    #   import: app/west.yml
    # - name: nice-view-gem #nice-gem
    #   remote: m165437 #nice-gem
    #   revision: main #nice-gem
  self:
    path: config
